### ISSUE TITLE
difference between the implementation and paper

### ISSUE THREAD

**Issue by yaoqi-zd** [huzi96/Coarse2Fine-ImaComp#1]
Hi, thanks for sharing your code!
I find the implementation of `h_synthesisTransformModelLoad` is different from that in the paper:
in your code:
```
class h_synthesisTransformModelLoad(tf.keras.Model):
  def __init__(self, num_filters, strides_list, conv_trainable=True, skip_level=-1, suffix='', prefix='', init_loader=None):
    super(h_synthesisTransformModelLoad, self).__init__()
    # your init code here
    # self.layer_1 = xxx
    # self.layer_2 = xxx
    # self.layer_3 = xxx
    # self.layer_4 = xxx

  def call(self, inputs):
    x0 = self.layer_1(inputs)
    x1 = self.layer_2(x0)
    x2 = self.layer_3(x1)
    x2 = tf.depth_to_space(x2, 2)
    x3 = self.layer_4(x2)
    return x3
```
in your paper:
the `depth_to_space` operation is right after the first deconv layer(layer_1).

May I ask why there exists such difference? Is the code of network definition complete enough for me to reproduce the performance in your paper?

Thx,
Qi Yao

**Comment by huzi96** [comment]
Hi,
Thank you for pointing out the difference. We are sorry that it exists. However, the difference is small and should not greatly influence the results.
Besides, the provided code and pre-trained models can reproduce the performance reported in the paper.  We will get it corrected in future updates.
