### ISSUE TITLE
why don't compress the frequency table

### ISSUE THREAD

**Issue by yaoqi-zd** [huzi96/Coarse2Fine-ImaComp#2]
Hi, I'm new to the image compression area. I've read your code and found that you only compress the priors and latent representations, i.e. z1, z2 and z3 in your code. 

Such strategy has the inefficiency that we have to run several synthesis transforms to get mu and sigma and decode z1, z2, z3 with frequency table constructed from mu, sigma.

so my question is why don't we just compress the latent representations, i.e. z3 and it's frequency table so that we only need to run synthesis transform once during decompress stage?

Thx in advance for your reply!
Qi Yao

**Comment by huzi96** [comment]
There are two reasons.
1. z1 and z2 are not just for estimating the frequency but they also contribute to the final reconstruction of the images. (see information aggregation reconstruction in the paper)
2. Though it is not thoroughly analyzed by experiments, intuitively, the direct compression of the frequency table can be inefficient, as even the parameter mu has the same dimensionality as z3 itself.

**Comment by yaoqi-zd** [comment]
@huzi96 figure it out, Thanks for your explanation!
