### ISSUE TITLE
About the bit ratio of z1, z2, and z3

### ISSUE THREAD

**Issue by ZhengxueCheng** [huzi96/Coarse2Fine-ImaComp#4]
Hi, thanks for releasing codes! I have read your paper and think it is very interesting. 
Could you please give some data about required bits for different scales z1, z2 and z3? Because I am curious about the proportion of overhead bits to the total bits.
Thanks:)

**Comment by huzi96** [comment]
The proportions of bits in each part differ from image to image
A typical ratio would be: 0.23%, 3.01%, 96.77% for z1, z2 and z3.

**Comment by ZhengxueCheng** [comment]
> The proportions of bits in each part differ from image to image
> A typical ratio would be: 0.23%, 3.01%, 96.77% for z1, z2 and z3.

Thank you very much for quick reply. Got it!
