### ISSUE TITLE
About the difference between model0 and model1

### ISSUE THREAD

**Issue by zmbhou** [huzi96/Coarse2Fine-ImaComp#5]
Hi, thanks for sharing the codes and models, it is really an interesting work. Two sets of models were released, I am wondering what is the difference between model0 and model1?

**Comment by huzi96** [comment]
Model0s are trained with MSE loss and optimized for PSNR-rate objectives. Model1s are with MS-SSIM and for MS-SSIM-rate evaluation.

**Comment by zmbhou** [comment]
Got it, thanks for your reply.
