### ISSUE TITLE
How i get the pdf version paper？

### ISSUE THREAD

**Issue by OpencvW** [huzi96/Coarse2Fine-ImaComp#6]
Hi，i cannot download the paper in google scholar，could you share me the pdf version paper？ thank you very much！

**Comment by huzi96** [comment]
The link seems to be deprecated. You may visit the correct AAAI proceeding via this link: [Link](https://aaai.org/ojs/index.php/AAAI/article/view/6736/6590)

**Comment by OpencvW** [comment]
Thanks for your reply
