### ISSUE TITLE
Points on the RD-Curve

### ISSUE THREAD

**Issue by rastaman7** [huzi96/Coarse2Fine-ImaComp#7]
Hello,
If possible, could you provide us the points(the value of x and y axis) on the RD-Curve "Figure 4. (b) Comparison on Kodak image set" on the paper? I would like to use them for comparison with other methods.

**Comment by huzi96** [comment]
Sure:
bpp - PSNR
0.2072 30.0631
0.2694 31.0654
0.3082 31.6113
0.3629 32.2974
0.4102 32.8406
0.4508 33.2612
0.4898 33.6535
0.7951 36.2269
1.0593 38.0253
1.2171 38.8963

bpp - MS-SSIM
0.2783 0.9771
0.4294 0.9860
0.5609 0.9897
0.6692 0.9919
0.7414 0.9928
0.8733 0.9942
1.2003 0.9962
1.4362 0.9971
1.5593 0.9975

Note that all average PSNR (MS-SSIM) values are calculated by computing an arithmetic mean over the PSNR (MS-SSIM) of all instances of images (24 images in total)

**Comment by rastaman7** [comment]
Thank you so much for the prompt reply.

**Comment by mosquitobite** [comment]
@huzi96 @rastaman7  Thanks for your data! Could you additionally provide us the points on the RD-Curve "Figure 4. (c) Comparison on Tecnick image set" on the paper?

**Comment by guoguo1314** [comment]
您好，能顺便给给clic数据集的点？谢谢哈！！

**Comment by huzi96** [comment]
Results on CLIC dataset (note that this is combining the mobile and professional set):

bpp - PSNR
[ 0.19384457, 32.99371085],
[ 0.21904684, 33.45755274],
[ 0.28536838, 34.49140415],
[ 0.55464888, 37.26209035],
[ 0.74801618, 38.76311242],
[ 0.87741394, 39.55085301],
[ 1.05560752, 40.59231226]

bpp - MS-SSIM
[ 0.22165698, 0.97834674],
[ 0.35615207, 0.98562604],
[ 0.47793141, 0.98901668],
[ 0.62259978, 0.99193628],
[ 0.74096972, 0.99329743],
[ 1.03776218, 0.99555306],
[ 1.25181141, 0.99649041],
[ 1.36933935, 0.99696643]

**Comment by guoguo1314** [comment]
好的，谢谢哥，祝你天天开心！！！aha

**Comment by guoguo1314** [comment]
突然发现你clic不是我想要的clic，我想要的是clic professional_valid_2020，里面有41张图那个，你代码我有点看不懂，所以不知道怎么测试。

**Comment by huzi96** [comment]
我帮你测，晚些时候给你结果

**Comment by guoguo1314** [comment]
好的，哥，祝你生十个大胖儿子

**Comment by huzi96** [comment]
Here you go:
Results on the 202 clic professional validation set (41 pics)
bpp - PSNR
[0.15360859, 34.11235228],
[0.22438802, 34.83270459],
[0.29442757, 35.46279542],
[0.5779806 , 37.4223737 ],
[0.78131466, 38.7738495 ],
[0.91276244, 39.50645024],
[1.09498735, 40.48299149]

bpp - MS-SSIM
[0.21494572, 0.97588244],
[0.33995646, 0.98372149],
[0.45261555, 0.98762547],
[0.60432187, 0.99146225],
[0.72509949, 0.99313321],
[1.03220965, 0.99608075],
[1.25310281, 0.99728458],
[1.37180624, 0.99779866]]

**Comment by guoguo1314** [comment]
> Here you go: Results on the 202 clic professional validation set (41 pics) bpp - PSNR [0.15360859, 34.11235228], [0.22438802, 34.83270459], [0.29442757, 35.46279542], [0.5779806 , 37.4223737 ], [0.78131466, 38.7738495 ], [0.91276244, 39.50645024], [1.09498735, 40.48299149]
> 
> bpp - MS-SSIM [0.21494572, 0.97588244], [0.33995646, 0.98372149], [0.45261555, 0.98762547], [0.60432187, 0.99146225], [0.72509949, 0.99313321], [1.03220965, 0.99608075], [1.25310281, 0.99728458], [1.37180624, 0.99779866]]

好的，谢谢哥，晚安诺

**Comment by guoguo1314** [comment]
![image](https://github.com/huzi96/Coarse2Fine-ImaComp/assets/57977189/1fb1b6e0-9c6c-4e7e-8059-1b2007acfca4)
学长，我有个疑问。我发现在High-Efficiency Lossy Image Coding Through Adaptive Neighborhood Information Aggregation的fig6 c您的是比cheng2020低的，如果是按照上面数据画出来的话是比cheng2020高了；第一个点，如果是0.15bpp，psnr是34.112，从这张图看是太强了。
数据集：https://data.vision.ee.ethz.ch/cvl/clic/professional_valid_2020.zip

**Comment by huzi96** [comment]
啊我PSNR算错了，重跑一下，稍等

**Comment by guoguo1314** [comment]
哈哈，麻烦学长了。手动狗头！

**Comment by huzi96** [comment]
Here you go:
bpp-PSNR
[0.15360859, 31.88385511],
[0.22438802, 33.26235119],
[0.29442757, 34.33872525],
[0.5779806 , 37.17813974],
[0.78131466, 38.69458373],
[0.91276244, 39.46479383],
[1.09498735, 40.46452185]

bpp-MS-SSIM
[0.21494572, 0.97588244],
[0.33995646, 0.98372149],
[0.45261555, 0.98762547],
[0.60432187, 0.99146225],
[0.72509949, 0.99313321],
[1.03220965, 0.99608075],
[1.25310281, 0.99728458],
[1.37180624, 0.99779866]

**Comment by guoguo1314** [comment]
好的，谢谢学长，祝你生活开心！！！
