### ISSUE TITLE
Testing results of Tecnick dataset

### ISSUE THREAD

**Issue by mosquitobite** [huzi96/Coarse2Fine-ImaComp#8]
Thanks for your sharing on testing results of Kodak Dataset! Could you additionally provide us the points on the RD-Curve "Figure 4. (c) Comparison on Tecnick image set" on the paper?

**Comment by huzi96** [comment]
Sure, here are the numbers.

0.14427, 34.91865
0.16020, 35.40760
0.20445, 36.57730
0.22300, 36.98078
0.24035, 37.33845
0.31685, 38.66251
0.37995, 39.44633
0.50715, 41.07926
0.59410, 41.93987
0.70537, 43.02070

**Comment by mosquitobite** [comment]
Thanks! BTW, could you share the Tecnick results for MSSSIM-optimized model?

**Comment by huzi96** [comment]
Follows are bpp and MS-SSIM results for MSSSIM-optimized models:

0.19764542, 0.98557571
0.30962861, 0.99167024
0.40482931, 0.99417071
0.51360292, 0.99562937
0.60055611, 0.99649946
0.82002444, 0.99774946
0.96970528, 0.99817985
1.03983347, 0.99845611

**Comment by mosquitobite** [comment]
Thanks a lot!
